jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-tarpaulin
      - run: cargo tarpaulin --no-fail-fast --out xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: nightly
      - run: cargo fmt --check && cargo clippy --all-features --all-targets --workspace
      - run: cargo test --all-features smd
name: main
on:
  - pull_request
  - push
